### ISSUE TITLE
Add programs related to DSA problems 

### ISSUE THREAD

**Issue by deniss-eh** [deniss-eh/DSA-HACKTOBERFEST#1]
Its open for all anyone can open pull request for this just mention https://github.com/deniss-eh/DSA-HACKTOBERFEST/issues/1 for linking this issue at the time opening the pull request. Make sure you guys add programs in proper folders. 

Edit : Make sure you guys make a proper quality program with proper comments and information included. Because quality matters. Happy Hacking :)

For more you look into this comment - https://github.com/deniss-eh/DSA-HACKTOBERFEST/pull/6#issuecomment-1277980541

**Comment by akashbiswas0** [comment]
@deniss-eh hey pls assign it to me

**Comment by srigundeti10** [comment]
Hey @deniss-eh  i have been searching regarding this and i have a list of questions at the ready.

**Comment by deniss-eh** [comment]
> @deniss-eh hey pls assign it to me

Its open for all anyone can open pull request for this just mention #1 for linking this issue at the time opening the pull request. Happy hacking!

**Comment by deniss-eh** [comment]
> Hey @deniss-eh i have been searching regarding this and i have a list of questions at the ready.

ya sure ask

**Comment by srigundeti10** [comment]
> > Hey @deniss-eh i have been searching regarding this and i have a list of questions at the ready.
> 
> ya sure ask

umm i meant i have questions for submition on DSA

**Comment by deniss-eh** [comment]
> > > Hey @deniss-eh i have been searching regarding this and i have a list of questions at the ready.
> > 
> > 
> > ya sure ask
> 
> umm i meant i have questions for submition on DSA

@srigundeti10 what question you have

**Comment by srigundeti10** [comment]
> > > > Hey @deniss-eh i have been searching regarding this and i have a list of questions at the ready.
> > > 
> > > 
> > > ya sure ask
> > 
> > 
> > umm i meant i have questions for submition on DSA
> 
> @srigundeti10 what question you have

umm so sorry for all the confusion but what i meant was that i have programs related to DSA problems and not that i have any questions.anyways thanks for asking again :)

**Comment by sangalgovind** [comment]
@deniss-eh plz assign it to me

**Comment by deniss-eh** [comment]
> > > > > Hey @deniss-eh i have been searching regarding this and i have a list of questions at the ready.
> > > > 
> > > > 
> > > > ya sure ask
> > > 
> > > 
> > > umm i meant i have questions for submition on DSA
> > 
> > 
> > @srigundeti10 what question you have
> 
> umm so sorry for all the confusion but what i meant was that i have programs related to DSA problems and not that i have any questions.anyways thanks for asking again :)

hmm ok.

**Comment by deniss-eh** [comment]
> @deniss-eh plz assign it to me

Buddy pls read this https://github.com/deniss-eh/DSA-HACKTOBERFEST/issues/1#issuecomment-1277936908

**Comment by HPatel08** [comment]
Please check my PR #12

**Comment by UtsavUpadhyay08** [comment]
Please check my PR #15

**Comment by UtsavUpadhyay08** [comment]
Hey @deniss-eh please check my PR #15

**Comment by Misbah-Ul-Haque** [comment]
@deniss-eh please assing this to me

**Comment by deniss-eh** [comment]
> @deniss-eh please assing this to me

Buddy read this - https://github.com/deniss-eh/DSA-HACKTOBERFEST/issues/1#issuecomment-1277936908

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?

**Comment by deniss-eh** [comment]
> Can you please assign this issue to me?

Buddy read this - https://github.com/deniss-eh/DSA-HACKTOBERFEST/issues/1#issuecomment-1277936908
