### ISSUE TITLE
Update documentations

### ISSUE THREAD

**Issue by deniss-eh** [deniss-eh/DSA-HACKTOBERFEST#2]
update documentations according to hacktoberfest.
documentation includes files like README.md , CODE_OF_CONDUCT.md , CONTRIBUTING.md , etc.
make sure to add this issue link to your pull request when opening a pull request for this issue

**Comment by burhanharoon** [comment]
Please assign this to me. I want to work on it

**Comment by deniss-eh** [comment]
> Please assign this to me. I want to work on it

ya sure buddy

**Comment by burhanharoon** [comment]
I'm on it!

**Comment by burhanharoon** [comment]
Just to be clear, You need a README.MD, CODE_OF_CONDUCT.md, and CONTRIBUTING.md files in your repo. Right?

**Comment by deniss-eh** [comment]
ya

**Comment by burhanharoon** [comment]
Got It!

**Comment by deniss-eh** [comment]
@burhanharoon pls update it as 2022 https://github.com/deniss-eh/DSA-HACKTOBERFEST#swags-of-hacktoberfest

**Comment by burhanharoon** [comment]
I'm talking about the swags of 2021 as the swags of 2022 are not announced yet. Therefore I wrote 2021.

**Comment by burhanharoon** [comment]
@deniss-eh should i change it to 2022?
